### ISSUE TITLE
Missing sognojq.my_retry package

### ISSUE THREAD

**Issue by pteixeiraubi** [sogno-platform/sogno-job-queue#1]
**Describe the bug**
Missing sognojq.my_retry package on setuptools

**To Reproduce**
2. Run on Python
```python
import sognojq
from sognojq.amqp import AmqpPublisher
from sognojq.my_retry import retry
```

**Expected behavior**
```python
from sognojq.amqp import AmqpPublisher
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sognojq/amqp.py", line 11, in <module>
    from sognojq.my_retry import retry
ModuleNotFoundError: No module named 'sognojq.my_retry'

from sognojq.my_retry import retry
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
**ModuleNotFoundError: No module named 'sognojq.my_retry'**
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Python 3.8.10

**Comment by pteixeiraubi** [comment]
Consider changing 
`packages=["sognojq"]`

into
`packages=["sognojq", "sognojq.my_retry"]`

on setup.py
